-- Squashed migration: Complete database schema
-- Generated by combining migrations 000001-000006

-- =============================================================================
-- USERS TABLE
-- =============================================================================
CREATE TABLE IF NOT EXISTS users (
    id BIGSERIAL PRIMARY KEY,
    auth0_id VARCHAR(255) UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL DEFAULT 'employee',
    title VARCHAR(255) NOT NULL DEFAULT '',
    department VARCHAR(255) NOT NULL DEFAULT '',
    avatar_url TEXT,
    supervisor_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    date_started TIMESTAMP WITH TIME ZONE,
    is_active BOOLEAN NOT NULL DEFAULT true,
    -- Jira integration fields
    jira_domain VARCHAR(255),
    jira_email VARCHAR(255),
    jira_api_token TEXT,
    jira_account_id VARCHAR(255),
    -- Jira OAuth fields
    jira_oauth_access_token TEXT,
    jira_oauth_refresh_token TEXT,
    jira_oauth_token_expires_at TIMESTAMP WITH TIME ZONE,
    jira_cloud_id VARCHAR(255),
    jira_site_url VARCHAR(255),
    -- Timestamps
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- User indexes
CREATE INDEX IF NOT EXISTS idx_users_auth0_id ON users(auth0_id);
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_supervisor_id ON users(supervisor_id);
CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);
CREATE INDEX IF NOT EXISTS idx_users_jira_account_id ON users(jira_account_id);
CREATE INDEX IF NOT EXISTS idx_users_is_active ON users(is_active);
CREATE INDEX IF NOT EXISTS idx_users_supervisor_active ON users(supervisor_id, is_active) WHERE is_active = true;
CREATE INDEX IF NOT EXISTS idx_users_role_active ON users(role, is_active) WHERE is_active = true;
CREATE INDEX IF NOT EXISTS idx_users_name_sort ON users(last_name, first_name);

-- =============================================================================
-- SQUADS TABLE
-- =============================================================================
CREATE TABLE IF NOT EXISTS squads (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- =============================================================================
-- USER-SQUADS JUNCTION TABLE
-- =============================================================================
CREATE TABLE IF NOT EXISTS user_squads (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    squad_id BIGINT NOT NULL REFERENCES squads(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    UNIQUE(user_id, squad_id)
);

CREATE INDEX IF NOT EXISTS idx_user_squads_user_id ON user_squads(user_id);
CREATE INDEX IF NOT EXISTS idx_user_squads_squad_id ON user_squads(squad_id);

-- =============================================================================
-- INVITATIONS TABLE
-- =============================================================================
CREATE TABLE IF NOT EXISTS invitations (
    id BIGSERIAL PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    token VARCHAR(64) NOT NULL UNIQUE,
    invited_by_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    status VARCHAR(50) NOT NULL DEFAULT 'pending',
    department VARCHAR(255),
    squad_ids BIGINT[],
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    accepted_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_invitations_email ON invitations(email);
CREATE INDEX IF NOT EXISTS idx_invitations_token ON invitations(token);
CREATE INDEX IF NOT EXISTS idx_invitations_status ON invitations(status);
CREATE INDEX IF NOT EXISTS idx_invitations_invited_by_id ON invitations(invited_by_id);
CREATE INDEX IF NOT EXISTS idx_invitations_status_expires ON invitations(status, expires_at) WHERE status = 'pending';

-- =============================================================================
-- ORG CHART DRAFTS TABLE
-- =============================================================================
CREATE TABLE IF NOT EXISTS org_chart_drafts (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    created_by_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    status VARCHAR(50) NOT NULL DEFAULT 'draft',
    published_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_org_chart_drafts_created_by_id ON org_chart_drafts(created_by_id);
CREATE INDEX IF NOT EXISTS idx_org_chart_drafts_status ON org_chart_drafts(status);
CREATE INDEX IF NOT EXISTS idx_org_chart_drafts_creator_updated ON org_chart_drafts(created_by_id, updated_at DESC);

-- =============================================================================
-- ORG CHART DRAFT CHANGES TABLE
-- =============================================================================
CREATE TABLE IF NOT EXISTS org_chart_draft_changes (
    id BIGSERIAL PRIMARY KEY,
    draft_id BIGINT NOT NULL REFERENCES org_chart_drafts(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    original_supervisor_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    original_department VARCHAR(255),
    original_role VARCHAR(50),
    original_squad VARCHAR(255),
    original_squad_ids BIGINT[],
    new_supervisor_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    new_department VARCHAR(255),
    new_role VARCHAR(50),
    new_squad VARCHAR(255),
    new_squad_ids BIGINT[],
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    UNIQUE(draft_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_org_chart_draft_changes_draft_id ON org_chart_draft_changes(draft_id);
CREATE INDEX IF NOT EXISTS idx_org_chart_draft_changes_user_id ON org_chart_draft_changes(user_id);
CREATE INDEX IF NOT EXISTS idx_org_chart_draft_changes_draft_updated ON org_chart_draft_changes(draft_id, updated_at DESC);

-- =============================================================================
-- ORGANIZATION JIRA SETTINGS TABLE
-- =============================================================================
CREATE TABLE IF NOT EXISTS org_jira_settings (
    id BIGSERIAL PRIMARY KEY,
    oauth_access_token TEXT NOT NULL,
    oauth_refresh_token TEXT NOT NULL,
    oauth_token_expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    cloud_id VARCHAR(255) NOT NULL,
    site_url VARCHAR(255) NOT NULL,
    site_name VARCHAR(255),
    configured_by_id BIGINT NOT NULL REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- =============================================================================
-- TASKS TABLE
-- =============================================================================
CREATE TABLE IF NOT EXISTS tasks (
    id BIGSERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    status VARCHAR(50) NOT NULL DEFAULT 'pending',
    due_date TIMESTAMP WITH TIME ZONE NOT NULL,
    start_time TIMESTAMP WITH TIME ZONE,
    end_time TIMESTAMP WITH TIME ZONE,
    all_day BOOLEAN NOT NULL DEFAULT TRUE,
    created_by_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    assignment_type VARCHAR(20) NOT NULL DEFAULT 'user',
    assigned_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    assigned_supervisor_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    assigned_department VARCHAR(255),
    assigned_squad_id BIGINT REFERENCES squads(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_tasks_created_by_id ON tasks(created_by_id);
CREATE INDEX IF NOT EXISTS idx_tasks_assigned_user_id ON tasks(assigned_user_id);
CREATE INDEX IF NOT EXISTS idx_tasks_assigned_supervisor_id ON tasks(assigned_supervisor_id);
CREATE INDEX IF NOT EXISTS idx_tasks_assigned_department ON tasks(assigned_department);
CREATE INDEX IF NOT EXISTS idx_tasks_assigned_squad_id ON tasks(assigned_squad_id);
CREATE INDEX IF NOT EXISTS idx_tasks_due_date ON tasks(due_date);
CREATE INDEX IF NOT EXISTS idx_tasks_status ON tasks(status);
CREATE INDEX IF NOT EXISTS idx_tasks_start_time ON tasks(start_time);
CREATE INDEX IF NOT EXISTS idx_tasks_end_time ON tasks(end_time);
CREATE INDEX IF NOT EXISTS idx_tasks_pending_due_date ON tasks(due_date) WHERE status != 'completed';
CREATE INDEX IF NOT EXISTS idx_tasks_due_date_assigned_user ON tasks(due_date, assigned_user_id);
CREATE INDEX IF NOT EXISTS idx_tasks_due_date_squad ON tasks(due_date, assigned_squad_id);
CREATE INDEX IF NOT EXISTS idx_tasks_due_date_department ON tasks(due_date, assigned_department);

-- =============================================================================
-- MEETINGS TABLE
-- =============================================================================
CREATE TABLE IF NOT EXISTS meetings (
    id BIGSERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    start_time TIMESTAMP WITH TIME ZONE NOT NULL,
    end_time TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    recurrence_type VARCHAR(20),
    recurrence_interval INT DEFAULT 1,
    recurrence_end_date TIMESTAMP WITH TIME ZONE,
    recurrence_days_of_week INT[],
    recurrence_day_of_month INT,
    parent_meeting_id BIGINT REFERENCES meetings(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_meetings_created_by_id ON meetings(created_by_id);
CREATE INDEX IF NOT EXISTS idx_meetings_start_time ON meetings(start_time);
CREATE INDEX IF NOT EXISTS idx_meetings_end_time ON meetings(end_time);
CREATE INDEX IF NOT EXISTS idx_meetings_parent_meeting_id ON meetings(parent_meeting_id);
CREATE INDEX IF NOT EXISTS idx_meetings_time_range ON meetings(start_time, end_time);
CREATE INDEX IF NOT EXISTS idx_meetings_time_creator ON meetings(start_time, created_by_id);

-- =============================================================================
-- MEETING ATTENDEES TABLE
-- =============================================================================
CREATE TABLE IF NOT EXISTS meeting_attendees (
    id BIGSERIAL PRIMARY KEY,
    meeting_id BIGINT NOT NULL REFERENCES meetings(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    response_status VARCHAR(20) NOT NULL DEFAULT 'pending',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    UNIQUE(meeting_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_meeting_attendees_meeting_id ON meeting_attendees(meeting_id);
CREATE INDEX IF NOT EXISTS idx_meeting_attendees_user_id ON meeting_attendees(user_id);

-- =============================================================================
-- TIME OFF REQUESTS TABLE
-- =============================================================================
CREATE TABLE IF NOT EXISTS time_off_requests (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    request_type VARCHAR(50) NOT NULL,
    reason TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    reviewer_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    reviewer_notes TEXT,
    reviewed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_time_off_user_id ON time_off_requests(user_id);
CREATE INDEX IF NOT EXISTS idx_time_off_status ON time_off_requests(status);
CREATE INDEX IF NOT EXISTS idx_time_off_dates ON time_off_requests(start_date, end_date);
CREATE INDEX IF NOT EXISTS idx_time_off_reviewer_id ON time_off_requests(reviewer_id);
CREATE INDEX IF NOT EXISTS idx_time_off_reviewer_reviewed_at ON time_off_requests(reviewer_id, reviewed_at) WHERE reviewer_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_time_off_user_status_dates ON time_off_requests(user_id, status, start_date, end_date);
CREATE INDEX IF NOT EXISTS idx_time_off_pending_created ON time_off_requests(status, created_at DESC) WHERE status = 'pending';
CREATE INDEX IF NOT EXISTS idx_time_off_approved_end_date ON time_off_requests(status, end_date) WHERE status = 'approved';

-- =============================================================================
-- OAUTH STATE STORE TABLE
-- =============================================================================
CREATE TABLE IF NOT EXISTS oauth_states (
    id BIGSERIAL PRIMARY KEY,
    state VARCHAR(64) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_oauth_states_state ON oauth_states(state);
CREATE INDEX IF NOT EXISTS idx_oauth_states_expires_at ON oauth_states(expires_at);
